version: '3.8'

networks:
  todo_net:

services:
  db:
    image: mariadb:latest
    container_name: todo_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - mariadb_data:/var/lib/mysql
      - ./config/mysql/encryption:/etc/mysql/encryption:ro
      - ./config/encryption.cnf:/etc/mysql/conf.d/encryption.cnf:ro
    command: 
      - --plugin-load-add=file_key_management
      - --file-key-management
      - --file-key-management-filename=/etc/mysql/encryption/keyfile
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo_net

  web:
    build: .
    container_name: todo_flask
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
      - "443:443"
    volumes:
      - ./app:/app
      - ./ssl:/app/ssl:ro
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}
      - SSL_CERT_PATH=/app/ssl/cert.pem
      - SSL_KEY_PATH=/app/ssl/key.pem
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo_net

volumes:
  mariadb_data:
    driver: local
