version: '3.8'

networks:
  todo_net:

services:
  mariadb:
    image: mariadb:latest
    container_name: todo_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopass123
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-prootpassword123"]
      retries: 5
      interval: 5s
    networks:
      - todo_net

  python_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: todo_python
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - todo_net
    volumes:
      - ./:/todolist

volumes:
  mariadb_data:
